### ISSUE TITLE
Optimization: Value handling operations

### ISSUE THREAD

**Issue by pepyakin** [paritytech/wasmi#101]
Related to #99 
Depends on #98

For now, functions like `into_little_endian` do an allocation. This is very unfortunate for the functions that are called upon every access to wasm memory.

At the very least, we can use change definition from

```rust
pub trait LittleEndianConvert where Self: Sized {
    fn into_little_endian(self) -> Vec<u8>;
    fn from_little_endian(buffer: &[u8]) -> Result<Self, Error>;
}
```

to something like this

```rust
pub trait LittleEndianConvert where Self: Sized {
    fn into_little_endian(&self, out: &mut [u8]); // Will panic if `out` of not appropriate size
    fn from_little_endian(buffer: &[u8]) -> Result<Self, Error>;
}
```

this will avoid allocations for `into_little_endian` case.

**Comment by CryZe** [comment]
I don't think you can do that just yet, because const generics aren't implemented yet. So `-> [u8; Self::N]` isn't a thing atm.

**Comment by pepyakin** [comment]
You're right, thank you! I've fixed the issue
