### ISSUE TITLE
API parity with browser/other engines

### ISSUE THREAD

**Issue by NikVolf** [paritytech/wasmi#125]
To achieve parity with alternate implementations of larger projects that happen to use `wasmi`, api surface of `wasmi` must be as close to browser engines as possible.

This includes (so far) API-s should be under feature flag:

- [ ] stop/resume
- [ ] memory used tracking (#153)

**Comment by Vurich** [comment]
We have suspend and resume functions, can this be closed?

**Comment by NikVolf** [comment]
@vurich they should be feature-gated imo

**Comment by Robbepop** [comment]
The `v1` implementation of `wasmi` (https://github.com/paritytech/wasmi/pull/287) re-implements the API of the well known Wasmtime crate and therefore implements this issue. The issue can be closed now.
