### ISSUE TITLE
Support returning strings

### ISSUE THREAD

**Issue by kpcyrd** [paritytech/wasmi#134]
I'm trying to write a function that returns a string, but right now I'm stuck. I wrote a function that I'm compiling to wasm:
```rust
#[no_mangle]
pub extern fn test3() -> *mut c_char {
    CString::new("ohai!").unwrap()
        .into_raw()
}
```

I'm calling it with wasmi like this:
```rust
let result = instance.invoke_export(
    "test3",
    &[],
    &mut exports,
).expect("failed to execute export");
println!("wasm returned: {:?}", result);
```

This returns:
```
wasm returned: Some(I32(1114120))
```

But it doesn't seem like there's a way to access the actual bytes. I can imagine some incredibly complex hacks to fit strings through an interface that only allows i32 by writing my own toy memory allocator, but I'd rather not do that.

Probably related to #88

**Comment by pepyakin** [comment]
yeah that could help, but at same time I actually wonder if we should put it in `MemoryInstance`. I'm afraid that it could become a swiss-knife. At the same time, this functionality could be implemented externally by using `with_direct_access`.

**Comment by stevemk14ebr** [comment]
See https://github.com/paritytech/wasmi/issues/256 for how to read strings from wasm

**Comment by Robbepop** [comment]
I will close this issue as it is quite outdated, @stevemk14ebr gave a link to an answer and we will probably not introduce a specialized API to ready out strings to our linear memory abstractions.
