### ISSUE TITLE
Decrease pointer-chasing/improve cache efficiency

### ISSUE THREAD

**Issue by Vurich** [paritytech/wasmi#136]
There are two problems, the way I see it:

1. Starting or resuming (after a nested call) a function call requires 4 derefs - instructions are a `Vec` in an `Rc` in an `Rc` in a `Vec`. This can blow the cache unless we're extremely lucky with where data gets allocated. Essentially, this means every function call requires up to 8 derefs which may be (and probably will be) on different cache lines. If we implemented TCO then tail calls would only require 4, but that's still bad.
2. The instructions are allocated in separate blocks, meaning more cache incoherency when changing function contexts (again, on calls and returns).

Since optimisers avoid function calls anyway and inline when possible (so the resultant wasm that we're executing should have minimal function calls) the impact of this is somewhat mitigated, but it's something that we can fix, so why not.

**Comment by Vurich** [comment]
So absolute best-case (if everything is in L1), some light googling pegs the speed of a single pointer read as 4 cycles. This is pipelined but it doesn't matter since we're dereferencing pointers-in-pointers and so it's inherently serial. https://www.edn.com/design/systems-design/4399725/Memory-Hierarchy-Design---Part-6--The-Intel-Core-i7

**Comment by Robbepop** [comment]
The `v1` implementation of `wasmi` (https://github.com/paritytech/wasmi/pull/287) now implements a Wasmtime inspired architecture and API and allocates all instructions of all functions in the same `Engine` instance in a single buffer. This heavily reduces the number of indirections from 4 down to 2 when given a `FuncBody` handle therefore closing this issue.
