### ISSUE TITLE
Allocate all instructions in single block

### ISSUE THREAD

**Issue by Vurich** [paritytech/wasmi#145]
My idea is to use a wrapper around a buffer with shared ownership, so each `Instructions` type has a pointer to a section of the buffer but the full buffer doesn't get dropped until all owners are dropped (similar to how `Bytes` works). Probably we would have to preallocate a buffer big enough to hold all instructions and then have some kind of `fn extend(iter: impl IntoIterator<Item = Instruction>) -> Option<BufferHandle>` (straw man naming, of course) that locks the shared buffer, writes the elements and then returns a handle that spans the newly-added elements. This avoids dealing with lifetimes and makes `Module::drop` much faster, at the cost of possibly making allocating a new module slower (we can either generate instructions in serial or generate them in parallel but use intermediate buffers that must then be copied from).

**Comment by Vurich** [comment]
Here's a sketch of what that would look like if we keep the restriction of denying unsafe code:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=223f92efd86137a3bd89770b045a11b8

**Comment by pepyakin** [comment]
What, can you define `all` for me?

**Comment by Vurich** [comment]
All within a single module, not all across all allocated modules.

**Comment by Robbepop** [comment]
The `v1` implementation of `wasmi` (https://github.com/paritytech/wasmi/pull/287) does allocate all instructions of all functions of the same `Engine` in a single buffer directly implementation the proposal of this issue. Therefore this issue can be closed now.
