### ISSUE TITLE
Cannot get tests to pass

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [paritytech/wasmi#159]
I'd like to send a PR with some changes, but I am unable to get the tests to pass - on MacOS with rust 1.32.0 and Linux with rust 1.24.0 and 1.32.0

The current versions I'm tring coincide with the latest builds on travie:
```
$ rustc --version
rustc 1.32.0 (9fda7c223 2019-01-16)
$ rustup --version
rustup 1.16.0 (beab5ac2b 2018-12-06)
$ cargo --version
cargo 1.32.0 (8610973aa 2019-01-02)
```

I've tried `cargo test` and `./test.sh` (which runs cargo test) and all 72 spec tests fail.

I looked at the .travis.yml file to see of there is any special setup required before running the tests but can't see anything nor in the README. Your matrix includes stable and nightly.

So, I'm stuck and not sure what's the issue.

Last build of master seems green (https://travis-ci.org/paritytech/wasmi/builds/481734745) but last build (derive branch) is red (https://travis-ci.org/paritytech/wasmi/builds/481862093)

**Comment by pepyakin** [comment]
The `derive` branch is really not in shape right now for its prime time and I just pushed it for the sake saving my progress : )

Have you tried tests on the master branch?

**Comment by andrewdavidmackenzie** [comment]
Yes, I forked and cloned and have tried on master of my clone.
In case it was my fork, or my changes, I tried re-cloning your repo directly (on Mac and then on Linux) and the same result on all three.

All spec tests fail with output like this:

```
---- spec::wasm_align stdout ----
running test: align
thread 'spec::wasm_align' panicked at 'Can't open file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1009:5
```

**Comment by andrewdavidmackenzie** [comment]
Aha! :-)

Is there some way I can figure out which?
Do you prefer to document it and/or a setup.sh script to create them for new users?

Let me know the magical encantations and I can try and document them for you....

**Comment by andrewdavidmackenzie** [comment]
BTW: how does Travis work? I don't see anything about sub-modules there....

**Comment by andrewdavidmackenzie** [comment]
@bkchr You are right! Not sure how I missed that! 
My only excuse is that I usually see that as a separate git command and that I missed the "--recursive" on the end of the clone. :-(
I've tried it and it works!
Sorry for the noise!
