### ISSUE TITLE
Understanding the interpreter build and no_std

### ISSUE THREAD

**Issue by jlb6740** [paritytech/wasmi#163]
Hi ... Basic understanding here. Very new to Rust and interested in running a tiny WASM interpreter. I am building wasmi with this command:

cargo rustc --release  --example interpret -- -C link-args=-Wl,-x -C opt-level=s
and then stripping symbols out with: "strip interpret" under the release/examples folder

I am trying to see how small I can make a standalone interpreter executable. Looking around it is suggested to use no_std to avoid including libstd which I've read should make my executable smaller (I am not sure of this because I don't know yet how to tell by looking at the cargo file what is being linked dynamically vs statically and I haven't confirmed in this case). I tried following the instructions here:

https://github.com/paritytech/wasmi#no_std-support

updating the cargo.toml: 
[dependencies]
parity-wasm = { version = "0.31", default-features = false, features = "core"}

But I immediately got a build error when following this direction:
Caused by:
  invalid type: string "core", expected a sequence for key `dependencies.parity-wasm.features`

So I changed the default build to core in the features section of the Cargo file like so:
[features]
default = ["core"]

At this point a new build takes place, but when I build the interpreter the size doesn't change. Also, if I just build the library with "cargo build" the size of the library changes very little (though it does get slightly bigger). 

Some questions are ... (1) am I building the wasmi interpreter with intended commands?  (2) When I build this interpret executable is it standalone or is it linking to the much larger wasmi library? (3) Should build core (building with no_std support) reduce the size of either the executable or the library?

Thanks

**Comment by pepyakin** [comment]
First of all I should clarify that wasm is meant to be used as a library. This is just because webassembly itself isn't capable of doing anything out-of-box due to its sandboxed nature. So I think you would first define the outer environment, and it depends on your use case.

The executables produced by rust are typically standalone and wasmi should be statically linked. 

`no_std` doesn't do anything except of removing the dependency on standard library. Without the standard library you are not able to interact with the operating system you are running on (if any). Building an example with `no_std` shouldn't have any noticeble difference compared to regular since they use `std`.

**Comment by jlb6740** [comment]
Hi .. thanks for the response. I will play around a bit. I was trying to reconcile then why the interpret binary is much smaller than the wasmi library but I I suppose that is only because the interpret binary doesn't use much from the library. I did still expect no_std to make the wasmi library much smaller. If I follow tutorials for using no_std and they replaced calls with crate libc (https://lifthrasiir.github.io/rustlog/why-is-a-rust-executable-large.html) to maintain some functionality you get from the standard library. Doing so substantially reduced the size for the simple example I was experimenting with and so I was expecting the wasmi library to show the same benefit when using no_std but it didn't. Your comments are a help. I will review further, looking to understand why not. If you have comments though let me know.

**Comment by jlb6740** [comment]
I will close this issue. Note I'd like to contribute updates targeting the no_std build, in particular that impact footprint.

Thanks
