### ISSUE TITLE
update to parity-wasm 0.39

### ISSUE THREAD

**Issue by richardanaya** [paritytech/wasmi#168]

**Comment by NikVolf** [comment]
parity-wasm of 0.35 contains a number of experimental features which must be filtered in wasmi (or in parity-wasm itself)

https://github.com/paritytech/parity-wasm/issues/265

**Comment by axic** [comment]
parity-wasm is at 0.38 now, yet wasmi is still at an ancient version.

Any plans updating the dependency?
