### ISSUE TITLE
Checking if NotStartedModuleRef has start without panicking

### ISSUE THREAD

**Issue by elichai** [paritytech/wasmi#172]
Hi,
I want to check if NotStartedModuleRef has a start function without panicking,
So I can't use `assert_no_start()` and don't want to use `not_started_instance()` without checking.
Can I make a PR that adds a function to check if it has start?
that way I can check before calling `not_started_instance()`

**Comment by pepyakin** [comment]
Hey! Yeah, I think that would be useful to have a function on `NotStartedModuleRef` to return if the module has the start function or not!

**Comment by elichai** [comment]
@pepyakin which name do you prefer? `have_start()` or `contains_start()`? or something else?

**Comment by pepyakin** [comment]
Both good with me : )
