### ISSUE TITLE
Automatically check for license headers

### ISSUE THREAD

**Issue by pepyakin** [paritytech/wasmi#195]
rustfmt can help with this check. An example can be found in the https://github.com/paritytech/ink repo.

**Comment by Robbepop** [comment]
While `rustfmt` provides the feature to check for this we cannot easily copy what we do at the ink! project because ink! uses _only_ the APACHE v2.0 license whereas `wasmi` uses _either_ APACHE v2.0 _or_ MIT license at the users choice.

**Comment by Robbepop** [comment]
I close this now since I have absolutely no clue how to do this with a double license situation like ours.
