### ISSUE TITLE
Keep parity-wasm up to date

### ISSUE THREAD

**Issue by DemiMarie-parity** [paritytech/wasmi#206]

**Comment by appcypher** [comment]
Can you provide more information on what you mean "up to date"?

**Comment by DemiMarie-parity** [comment]
Generally, we should bump each dependency to the latest version soon after a new version of the dependency is released.

**Comment by pepyakin** [comment]
Yeah, agree.

Although, I am going ahead and closing this issue, since since its creation the dependencies have been bumped 2 times already.
