### ISSUE TITLE
problems building for no_std enviroment 

### ISSUE THREAD

**Issue by kfessel** [paritytech/wasmi#218]
wasmi uses num_rational::BigRational for float conversion since 7fe6ef4e355faac97c66a691ea96e99eccb73e22 
BigRational needs the bigint or bigint-std but the no_std version does not work at the moment :
from num-rational release-notes:
> In the future, it may be possible to use the bigint feature with no_std

this way num-rational forces std since thes is no bigint for no_std

**Comment by thiolliere** [comment]
side note: bigint could be supported on no_std with https://github.com/rust-num/num-bigint/pull/101

**Comment by mystor** [comment]
This should be fixed now that #230 has been merged.
