### ISSUE TITLE
Structured error types

### ISSUE THREAD

**Issue by NikVolf** [paritytech/wasmi#23]
Many applications of the interpreter can handle some error in a meaningful way (memory access violation, extern signatures mismatch, etc.), so it makes sense to encode them in other than a heap allocated string

**Comment by pepyakin** [comment]
Yep, agree. However, I think that we should hold on with this. At the time, it is not so clear what exact variant should have this additional data and so as not clear what additional data users would need.
I think it would be better to hold on with this at the time.

However, what we can do now, is at least differentiate between different traps (cc https://github.com/pepyakin/wasmi/issues/26), like: linear memory oob access, function type differs from expected in `indirect_call`, explicit trap with `unreachable`, etc

**Comment by Robbepop** [comment]
I don't know the difference between this issue and https://github.com/paritytech/wasmi/issues/177 but the `v1` implementation of `wasmi` (https://github.com/paritytech/wasmi/pull/287) now supports proper error types without usage of `String` internally. So this issue can be closed now.
