### ISSUE TITLE
Consider implementing Send for ModuleInstance

### ISSUE THREAD

**Issue by That3Percent** [paritytech/wasmi#231]
I am working on an application that exposes as a part of its host bindings functions which do asynchronous IO. It would be great to be able to suspend the execution of the module, have the current thread move on to other tasks, and resume execution on another thread when the IO is complete (basic async/await Rust stuff).

I'm not yet sure how big a lift that story would be, but the first problem that I'm running into is that `ModuleInstance` does not impl `Send` because `GlobalRef` contains an `Rc`.

**Comment by pepyakin** [comment]
Hello! Sorry for the late reply.

Generally, I would be up to do that, however I am not yet sure how to achieve that cleanly without regressing the performance too much. I think it might be achievable by using `Arc` with careful caching of the pointers inside of the main interpreter loop (i.e. runner.rs), but I haven't really digged into that.

**Comment by Robbepop** [comment]
The `v1` implementation of `wasmi` (https://github.com/paritytech/wasmi/pull/287) has a radically different architecture so `Instance` (formerly known as `ModuleInstance`) is trivially `Send` now.
