### ISSUE TITLE
Accessing memory of WASM module

### ISSUE THREAD

**Issue by ethindp** [paritytech/wasmi#256]
I'm trying to implement logging into my Wasm module. However, I've no idea how to actually get access to the memory of the module. For example, if I have an export:
```rust
extern {
    fn log_error(text: *mut c_str);
}
```
And I call it using CString, the host is going to get a memory offset. Is there a function to get direct access to the memory of the module? (I couldn't find it so that's why I'm asking.) Also, how would I determine the length of the string?

**Comment by stevemk14ebr** [comment]
You may do the following:

WASM:
```
extern {
    pub fn log_impl(msg: *const u8, msg_len: u32);
}

fn log(msg: &str) {
    unsafe {
        log_impl(msg.as_ptr(), msg.len() as u32)
    }
}

log("Hello from Wasm");
```

Runtime:
```
pub fn read_wasm_string(offset: u32, length: u32, wasm_mem: &[u8]) -> &str {
    core::str::from_utf8(&wasm_mem[offset as usize..offset as usize + length as usize]).expect("read_wasm_cstring failed to parse invalid utf-8 string")
}

impl Externals for Runtime {
    fn invoke_index(
        &mut self,
        index: usize,
        args: RuntimeArgs,
    ) -> Result<Option<RuntimeValue>, Trap> {
    let direct_mem = self.memory.direct_access();
    let wasm_direct_mem = direct_mem.as_ref();

    match index {
         FUNCIDX_LOG => {
                let addr: u32 = args.nth_checked(0)?;
                let length: u32 = args.nth_checked(1)?;

                let string = read_wasm_string(addr, length, &wasm_direct_mem);
                (self.log_routine)(string);
                Ok(None)
            },
    }
}
```

where memory is an export by name as per wasm modules usually have:
```
let memory_export = main.export_by_name("memory").ok_or(wasmi::Error::Validation("memory export missing".to_string()))?;
let memory = memory_export.as_memory().ok_or(wasmi::Error::Validation("memory export not a memory type".to_string()))?;
```

**Comment by ethindp** [comment]
Ah, okay. Thank you!

**Comment by yavko** [comment]
Runtime seems to not exist, is it gone in newer versions? Is this still possible in newer versions, and how?

**Comment by Robbepop** [comment]
Not sure I understand your question but `wasmi` API has changed significantly since the creation of this issue.
We are now mirroring the well established and battle tested Wasmtime API.
If you want to access the `Memory` of an instantiated Wasm module you can use this API: https://docs.rs/wasmi/0.29.0/wasmi/struct.Instance.html#method.get_memory
