### ISSUE TITLE
Configuring memory usage for no_std use cases

### ISSUE THREAD

**Issue by barafael** [paritytech/wasmi#259]
Hi :)

I have managed to run wasmi with no_std on a rather beefy microcontroller. Can be seen [here](https://github.com/barafael/wasm-on-mcu).

I am using CortexMHeap as allocator. Initially, RAM usage was way to high. 

The memory usage seems to be determined by `DEFAULT_VALUE_STACK_LIMIT` and `DEFAULT_CALL_STACK_LIMIT`. So I reduced these initial values (can be seen [here](https://github.com/barafael/wasmi). This was enough to get basic WASM functions to run on the MCU target :) Awesome.

What do you think about exposing the used memory over the public API? Either at runtime with something like `.with_value_stack_limit(usize)` or with const generics on `StackRecycler`?

**Comment by pepyakin** [comment]
Can you expand the proposal with `with_value_stack_limit`?

**Comment by barafael** [comment]
Actually, it's already there - StackRecycler::with_limits. But the only usage AFAICT is in the implementation of Default for StackRecycler, where the default values from above are used. 

This could be done like this:

```rust
let stack_rec = StackRecycler::with_limits(84 * 1024, 84 * 1024);
let func_ref = instance.export_by_name("color").unwrap().as_func().unwrap();
let interpreter = wasmi::runner::Interpreter::new(func_ref, &[RuntimeValue::I32(13)], Some(&mut stack_rec));
```
This only does not work because the module `runner` is private.

Essentially, what I am looking for is just some way to control the size of StackRecycler from the outside :)

**Comment by pepyakin** [comment]
Right, but [`StackRecycler`](https://docs.rs/wasmi/0.9.0/wasmi/struct.StackRecycler.html) is nonetheless accessible? Isn't that sufficient?

**Comment by barafael** [comment]
Just given the recycler, how would I access the interpreter?

**Comment by pepyakin** [comment]
Why would you need that? The typical flow is to call into the wasm instance via an `Func`, and for your use case it seems that [`invoke_with_stack`](https://docs.rs/wasmi/0.9.0/wasmi/struct.FuncInstance.html#method.invoke_with_stack) should suffice. There is also convenience functions defined on the [`ModuleRef`](https://docs.rs/wasmi/0.9.0/wasmi/struct.ModuleRef.html#method.invoke_export_with_stack)

**Comment by barafael** [comment]
Oh perfect, thanks for that! I'll look into it but it seems this is exactly what I need.

**Comment by barafael** [comment]
works perfectly! Thanks.
