### ISSUE TITLE
Continuous fuzzing with OSS-Fuzz?

### ISSUE THREAD

**Issue by conradgrobler** [paritytech/wasmi#268]
Have you considered integrating the wasmi fuzz targets with OSS-Fuzz(https://github.com/google/oss-fuzz) to enable continuous fuzzing?

Given that there are existing fuzz targets defined, it should be relatvely straight-forward to integrate. See https://google.github.io/oss-fuzz/getting-started/new-project-guide/rust-lang/ for more info.

**Comment by Robbepop** [comment]
For now I do not want to support multiple different fuzz testers. We are fine with the default Rust/Cargo fuzz testing infrastructure with support from BytecodeAlliance's `wasm-smith`. Maybe in the future we may consider to have more different fuzzers. In that case I might reopen this issue or open yet another concrete issue.
