### ISSUE TITLE
What is the status of the project?

### ISSUE THREAD

**Issue by sudeepdino008** [paritytech/wasmi#269]
Hey, wanted to check on the status of the project in the context of the overall Web3 work that's happening.  
Secondly, is there something I can work on here? I'm interested in learning Rust and Webassembly, wanted to implement something challenging.

**Comment by athei** [comment]
You can consider wasmi being in "maintenance mode". No substantial resources are poured into it in order to implement new features because we want to eventually replace it by wasmer singlepass.

**Comment by Robbepop** [comment]
Question was answered. Closed.
