### ISSUE TITLE
Add origin information about Wasm traps

### ISSUE THREAD

**Issue by tailhook** [paritytech/wasmi#28]
Hi,

Is there any way to debug where trap happened? At least function would be good, file+line and/or traceback is even better.

I'm using rust's wasm32-unknown-unknown for generating wasm code itself (and the trap is a panic). Maybe that's something to tweak at the compiler side?

**Comment by pepyakin** [comment]
In general, there is no way to get location of the trap yet (although this should be very useful, and I think this is somwthing we want sooner rather than later)

However, it is possible to print information provided in panic payload, at least if you have a custom panic fmt. But im not sure how panics are reported in wasm32-unknown-unknown with std.

**Comment by tailhook** [comment]
> However, it is possible to print information provided in panic payload, at least if you have a custom panic fmt. But im not sure how panics are reported in wasm32-unknown-unknown with std.

It looks like payload is ignored by rust compiler: https://github.com/rust-lang/rust/blob/master/src/libpanic_unwind/wasm32.rs#L28

Also, what do you mean by "print"? I don't think there is some builtin way to print something in wasm.

**Comment by pepyakin** [comment]
AFAIK, actual printing happens in the panic hook, ie [here](https://github.com/rust-lang/rust/blob/92c32d2d8ca4dc7fb8ddf9296580b0c573350c6a/src/libstd/panicking.rs#L370) which happens before `libpanic_*` takes control (just take a look at other impls or at libpanic_abort).

> Also, what do you mean by "print"? I don't think there is some builtin way to print something in wasm.

Yeah, you're right! However, in some envs such as web JS or wasmi we can define what it means to print something.
In fact, wasm std lib supports basic i/o however under special flag [`DEBUG`](https://github.com/rust-lang/rust/blob/70f7d5842f29d4900f24420b030f144d21f3c5fc/src/libstd/sys/wasm/mod.rs#L39)

Hope this helps!

**Comment by tailhook** [comment]
Wow, that worked like a charm! Thanks. [Here is the code](https://github.com/tailhook/verwalter/commit/82d16ad9b86a1cdf8b7018c1f084f142cc09d902) that catches panics and logs payload and location for anyone trying to figure it out.

However, I think this issue (i.e. tracking traps and not only panics out of the box) depends on [debugging symbols](https://github.com/rust-lang-nursery/rust-wasm/issues/26) and should not be closed yet. Right?

**Comment by pepyakin** [comment]
Im very happy thats worked!

And yea, you right, we still need to have means to debug different kinds of traps and print stacktraces. And yeah it depends on debugging symbols (although plain name section should do the trick for the start)

**Comment by Robbepop** [comment]
Closed in favor of https://github.com/paritytech/wasmi/issues/538.
