### ISSUE TITLE
Implement support for running `wasm32-wasi` compiled Wasm binaries

### ISSUE THREAD

**Issue by Robbepop** [paritytech/wasmi#358]
The [WebAssembly System Interface (WASI)](https://github.com/WebAssembly/WASI) is an important part at enabling support for a wide variety of WebAssembly targets.
With `wasmi_v1` and its `Linker` definition it should be very straight forward to implement WASI support for the `wasmi` interpreter.

Ideally the entire WASI implementation resides in a new sub-crate of the `wasmi` workspace, called `wasi`.
This sub-crate implements the WASI interface and provides extension methods for the `wasmi_v1::Linker` to add WASI support.

As a follow-up feature we could provide an executable for `wasmi_v1` that runs input `.wasm` or `.wat` files using WASI support out of the box as it is done in Wasmtime.

As an overview of what needs to be implemented you can inspect: https://doc.rust-lang.org/std/os/wasi/index.html
The [Wasmtime implementation of WASI](https://docs.rs/wasi-cap-std-sync/0.34.0/wasi_cap_std_sync/) is also a place to look out for inspiration. Technically we could also use it as a common ground for our WASI support.

Wasmtime reference API guide: https://docs.wasmtime.dev/examples-rust-wasi.html
WASI proposals: https://github.com/WebAssembly/WASI/blob/main/Proposals.md

**Comment by OLUWAMUYIWA** [comment]
Would certainly love to work on this @Robbepop

**Comment by Robbepop** [comment]
> Would certainly love to work on this @Robbepop

I would certainly appreciate help with this issue!
Please feel free to let me know what you need to know and how I can help you with work on this. :)

> As a follow-up feature we could provide an executable for wasmi_v1 that runs input .wasm or .wat files using WASI support out of the box as it is done in Wasmtime.

The situation here has significantly improved since creation of the issue since we now have `wasmi_cli` which is a CLI tool to invoke `.wasm` and `.wat` files using `wasmi`. Therefore as a follow-up we really would love for this CLI tool to have WASI support out of the box.

**Comment by OLUWAMUYIWA** [comment]
Thanks!
I will implement it in drafts. If I need help, I'll let you know.

**Comment by Robbepop** [comment]
In case you were not already aware of the Wasmtime `wasi-common` crate:
https://crates.io/crates/wasi-common/1.0.0

I think it might suite as a good foundation for WASI support in `wasmi`.

**Comment by OLUWAMUYIWA** [comment]
Yes I found it while looking around. I'm making use of it. Thanks!

**Comment by Robbepop** [comment]
@OLUWAMUYIWA how is it going with the `wasmi` WASI implementation so far? Do you need any help or can we somehow support you?

**Comment by OLUWAMUYIWA** [comment]
Hi Rob. Apologies. I got stuck at some point. Rather than getting unstuck, I paused and got busier. Still interested. Will pick it up again tomorrow, and ask you some questions. Is there a discord?

**Comment by Robbepop** [comment]
Thank you for the response @OLUWAMUYIWA . Looking forward to answer all your questions. :)

**Comment by Robbepop** [comment]
@OLUWAMUYIWA I just sent you an e-Mail with my Discord handle. :)
