### ISSUE TITLE
Ensure `load` fuzz target works robustly

### ISSUE THREAD

**Issue by pepyakin** [paritytech/wasmi#37]
For now, there is a few problems with that `load` fuzz target detects, particulary in parity-wasm:

- [x] https://github.com/paritytech/parity-wasm/issues/151
- [x] https://github.com/paritytech/parity-wasm/issues/159
- [ ] https://github.com/paritytech/parity-wasm/issues/194

**Comment by NikVolf** [comment]
I think you should pick some other wabt version which does not allow experimental features (atomic opcodes, shared memory, etc.)

**Comment by pepyakin** [comment]
That bug with shared memory passes validation was fixed, see https://github.com/WebAssembly/wabt/issues/754.
