### ISSUE TITLE
Test for no_std availability in builds tests

### ISSUE THREAD

**Issue by chrysn** [paritytech/wasmi#374]
The build tests that currently run as "no_std" do not check what they should check for -- that the project can actually be built without std: They do disable the std feature from the present crates by adding `--no-default-features`, but any crate that is no_std can just pull in std, and the CI would be none the wiser.

Unless there is a better way to detect (and fail on) the presence of std, a simple way to perform the test better is to run the no_std build with `--target thumbv7em-none-eabihf`, for which (unlike the wasm32-unknown-unknown) there is no std library available, and thus depending transitively on std does cause a hard build failure.

Fixing the test alone will likely uncover issues down the dependency chain -- my current attempts to build showed numerous errors in core/src/nan_preserving_float.rs (maybe also triggered by the presence of an own crate named "core"?), and the spin and wasmparser-nostd crates. (Currently you'd probably only ever want to look at the first error produced; the latest compilers regressed in the amount of follow-up errors they print).

**Comment by hussein-aitlahcen** [comment]
There is a missing `#![no_std]` in `wasmi_core` :)

**Comment by hussein-aitlahcen** [comment]
cc @Robbepop

**Comment by Robbepop** [comment]
Oh wow!
I actually had to check the codebase locally to make sure that this is real.
Thanks for the fix!

**Comment by hussein-aitlahcen** [comment]
@Robbepop we can close this :)

**Comment by chrysn** [comment]
If you want to automate testing this, a line of `cargo +nightly build --target thumbv7em-none-eabi --no-default-features --lib` or similar (main point: the "none" is a pretty strong indication that there won't be a std for this target) helps enforcing this property in CI.

**Comment by Robbepop** [comment]
@chrysn can you file a PR for this?
