### ISSUE TITLE
`wasmi-validation 0.4.2` was yanked

### ISSUE THREAD

**Issue by ukint-vs** [paritytech/wasmi#395]
Since `wasmi-validation` version has been updated to 0.5.0 and 0.4.2 has been yanked. `wasmi 0.12.0` cannot be built from crates.io because it has a dependency `wasmi-validation 0.4.2`.

https://crates.io/crates/wasmi/0.12.0/dependencies

**Comment by bkchr** [comment]
CC @Robbepop

**Comment by Robbepop** [comment]
Unfortunately we had to yank `wasmi-validation`0.4.2. I will prepare a `wasmi` v0.13 release.
