### ISSUE TITLE
Fuzz execution

### ISSUE THREAD

**Issue by pepyakin** [paritytech/wasmi#4]
I think we want to fuzz our interpreter with fuzzer ([wasm-opt --translate-to-fuzz](https://docs.rs/binaryen/0.3.0/binaryen/tools/fn.translate_to_fuzz.html)?). AFAIK, it is capable of producing executable inputs.

**Comment by Robbepop** [comment]
I will close this as we already have 2 disfunctional fuzzers and want to build our next fuzzing system on Wasmtime's `wasm-mutate` and `wasm-smith` utilities.
