### ISSUE TITLE
Does wasmi supporting canonicalize_nans ?

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/wasmi#403]
I think it maybe support it because it could run substrate runtime, but I could not find it.

**Comment by Robbepop** [comment]
We use these floating point types in `wasmi` for exactly that purpose:
https://github.com/paritytech/wasmi/blob/master/core/src/nan_preserving_float.rs

**Comment by yjhmelody** [comment]
Thanks, I will read these.
