### ISSUE TITLE
Decouple `wasmi` crates

### ISSUE THREAD

**Issue by Robbepop** [paritytech/wasmi#416]
Right now we have two crates in the `wasmi` workspace:

- `wasmi_core`: Which defines primitive types for `wasmi`, so actually it should be renamed to `wasmi_primitives`.
- `wasmi`: Which includes everything else.

"Everything else" certainly smell like we should break this big crate up into several smaller pieces.
But what are those smaller pieces?

The `wasmi` crate currently has the following responsibilities:

1. It defines a Wasm module structure.
1. It defines an API to parse user provided Wasm bytecode.
1. It hosts a Wasm engine and therefore allows to execute Wasm bytecode.

All of these could potentially be broken down into their own crates with just that repsonsibility.
The following picture describes the organization of the workspace with decoupled crates:

![2022-08-27-122852_1555x948_scrot](https://user-images.githubusercontent.com/8193155/187026247-1bc3590c-8d9a-42dd-81d3-88e87ffa96e1.png)

- `wasmi_parse` has the responsibility to parse user provided Wasm bytecode and forward it to the sub-crates responsible for further processing.
- `wasmi_module` provides Wasm module definitions. This includes all of the `Module`, `Store`, `Instance`, `Memory` etc. type definitions and their behaviors.
- `wasmi_primitives` is just the former `wasmi_core` but renamed to a better fitting name.
- `wasmi_engine` is an umbrella crate that defines interfaces for `wasmi` compatible Wasm execution engines. This allows us to have multiple Wasm execution engines working for `wasmi`.
- `wasmi_stackmach` is a simple stack-machine based Wasm execution engine optimized for efficient compilation efficiency at the cost of execution efficiency.
- `wasmi_regmach` is a complex register-machine based Wasm execution engine optimized for fast execution efficiency at the cost of translation efficiency.
- Then we also still have the `wasmi` crate which is just an umbrella crate that includes all the other crates, acts as glue and provides a user friendly API for them.

## ToDo

- [x] https://github.com/paritytech/wasmi/issues/491

**Comment by yjhmelody** [comment]
Hi, Will you consider wasm memory as a crate?

**Comment by Robbepop** [comment]
The information and design chosen in this issue is highly outdated. We chose to not support multiple engine backends and instead have a single one that fits our target use cases as best as possible.
Also some decouplings are way harder than originally anticipated.
