### ISSUE TITLE
Unexppected NaN

### ISSUE THREAD

**Issue by erxiaozhou** [paritytech/wasmi#435]
# Build commands
I compile the code with commit id 3b29737f7aa5faaeb0c14cd38c4dd1339e72f597.
Platform: Ubuntu 20.04
CPU: amd64
compile:
```shell
cargo build
```
execute:

```shell
wasmi_cli cp907_b3.wasm _start
```
[cp907_b3.zip](https://github.com/paritytech/wasmi/files/9548016/cp907_b3.zip)

# Expected behavior:
It seems that the output should be -nan, with a value 0xffcefef4  left on the stack

# Actual behavior:
wasmi output:
```
NaN
```
and the value left on the stack is 0xff8efef4

Thank you.

**Comment by Robbepop** [comment]
Thanks a lot for reporting and providing the failing test input. I will take a look. What version of wasmi did you use?

**Comment by erxiaozhou** [comment]
> Thanks a lot for reporting and providing the failing test input. I will take a look. What version of wasmi did you use?

Thank you for your reply. The commit id of tested wasmi is 3b29737f7aa5faaeb0c14cd38c4dd1339e72f597.

**Comment by Robbepop** [comment]
Minified `.wasm` test file:
```wat
(module
  (type (;0;) (func (result f32)))
  (func (;2;) (type 0) (result f32)
    f32.const -nan:0xefef4 (;=-nan;)
    f32.const -0x1.44ceeep+127 (;=-2.15872e+38;)
    f32.copysign
  )
  (export "_start" (func 0))
)
```

**Comment by erxiaozhou** [comment]
> Minified `.wasm` test file:
> 
> ```webassembly
> (module
>   (func (export "_start") (param) (result f32)
>     (f32.copysign
>         (f32.const -nan:0xefef4)
>         (f32.const -1)
>     )
>   )
> )
> ```
> 
> Currently trying to understand what is going on. So far it seems to me that `wasmi`'s `copysign` implementation behaves correctly. Why are you expecting the whole run to return `0xFFCEFEF4` instead of `0xFF8EFEF4`?
> 
> Given that:
> 
> * `(f32.const -nan:0xefef4)` translates to `0xFF8EFEF4`
> * `(f32.const nan:0xefef4)` translates to `0x7F8EFEF4`
> 
> Note that the first bit is the sign bit.
> 
> What I found so far is that Rust prints `"NAN"` for both `f32::NAN` as well as `-f32::NAN` which is confusing.
> 
> The official WebAssembly spec test suite contains the following (very similar) tests that `wasmi` passes:
> 
> ```webassembly
> (assert_return (invoke "copysign" (f32.const -nan) (f32.const -0x0p+0)) (f32.const -nan))
> (assert_return (invoke "copysign" (f32.const -nan) (f32.const 0x0p+0)) (f32.const nan))
> ```
> 
> Changing the `Display` impl of `wasmi`'s `F32` and `F64` types to
> 
> ```rust
> impl ::core::fmt::Display for $for {
>     fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
>         if <$is>::from(*self).is_nan() && <$is>::from(*self).is_sign_negative() {
>             ::core::write!(f, "-NaN")
>         } else {
>             <$is as ::core::fmt::Display>::fmt(
>                 &<$is as ::core::convert::From<Self>>::from(*self),
>                 f,
>             )
>         }
>     }
> }
> ```
> 
> Changes the output of `wasmi_cli cp907_b3.wasm _start` to the expected `-NaN`.

Get it. Thank you for your patience and nice reply!

**Comment by Robbepop** [comment]
@erxiaozhou closing this now since your issue seems to be resolved.
