### ISSUE TITLE
Mutably Borrow Host Data & Memory Data Separately

### ISSUE THREAD

**Issue by AldaronLau** [paritytech/wasmi#447]
It would be nice if there was a way to mutably borrow the application-provided state while also borrowing memory from the `Caller`.

In the code I'm writing right now there's a lot of borrowing back-and-forth of:

```rust
caller.host_data_mut()

memory.data_mut(&mut caller)
```

Except, now I'm running into an issue where I need both at the same time.  This *can* be fixed with an `Arc` wrapper around the state, but I think it would be nicer if there was a way to separate the two.

**Comment by Robbepop** [comment]
Wasmtime exposes this API: https://docs.rs/wasmtime/0.40.1/wasmtime/struct.Memory.html#method.data_and_store_mut

Maybe that would help you out?

**Comment by AldaronLau** [comment]
Yeah, that API would be perfect!

**Comment by Robbepop** [comment]
Okay then I am open to it being implemented for `wasmi`. I might do that myself but I also accept PRs.

**Comment by Robbepop** [comment]
https://github.com/paritytech/wasmi/pull/448 was merged so this can be closed. Thanks again @AldaronLau !
