### ISSUE TITLE
CI: Stabilize continuous benchmarking runs

### ISSUE THREAD

**Issue by Robbepop** [paritytech/wasmi#495]
We have a benchmarking CI that checks the `wasmi` performance for native and Wasmtime based Wasm execution.
The CI based benchmarking is pretty useful in itself and provides us with plenty of information that helps us to improve the performance of `wasmi` further.
However, there is one major problem: The CI based benchmark results are extremely noisy. Even PRs that have absolutely no impact on the performance of `wasmi` show significant noise in those benchmarks and PRs that generally are expected to improve performance (at least verified on different hardware locally) actually shows mostly regressions: https://github.com/paritytech/wasmi/pull/493#issuecomment-1265289606

There may be many different causes for this. A few of my uneducated guesses are the following:

- Benchmarks may be running concurrently on the same hardware.
    - We are talking about actual hardware, not container, not VM, not any other means of virtualization etc.
    - Also on a machine with many cores we still should only run a single benchmark since benchmarks may invalidate each others caches.
- There may be other entirely different jobs running on the hardware at the time of the benchmark execution.

Generally for our CI based benchmarks we need guarantee that our benchmarking job is really the only one that is running on the same hardware at the same time.

**Comment by sergejparity** [comment]
Experiment showed that most suitable gitlab-runners from our fleet, to run benchmarks are runners based on [GCE c2-standard-16](https://cloud.google.com/compute/docs/compute-optimized-machines#c2_machine_types) VM's they offer sustainable performance and low variability results
