### ISSUE TITLE
Make `wasmi` bytecode instruction naming consistent

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/wasmi#504]
For instruction suffixed with`_s`/`_u` in wasm spec, there are some instructions named like this style: `f32.convert_i32_u` `F64ConvertUI32` while some are like this: `I32TruncSatF32S`.

**Comment by Robbepop** [comment]
That's true and a result of my trying to be genius at first and copying whatever LLVM does to name their instructions just to later find out that it wasn't genius at all and we should have just stick to the Wasm naming scheme.
