### ISSUE TITLE
Reconsider the limits

### ISSUE THREAD

**Issue by pepyakin** [paritytech/wasmi#51]
We need to reconsider the limits (particularly maximal value and frame stack height).
Ideally we should provide a way for a user to change this limits.

Also, we might want to synchronize with limits.h

**Comment by bddap** [comment]
`Interpreter::new` creates new value stack with size `DEFAULT_VALUE_STACK_LIMIT`.

`Interpreter::run_interpreter_loop` checks it's frame stack against `DEFAULT_CALL_STACK_LIMIT`.

I think the first step should be `Interpreter::new` taking value stack limit and frame stack limit as arguments.

**Comment by bddap** [comment]
Ok, backing out of the weeds here.

On a higher level, It seems like `ModuleInstance` should hold value and frame stack limits. That way the user can optionally set those values in when they create the module.

**Comment by pepyakin** [comment]
I would disagree here.

1. A user may want to execute two functions on a same instance with two different limits.
2. One instance is able to call functions on other instance. This raises a question, when calling an instance with different limits should you preserve limits from the calling instance or should you just adjust to a new limits?

In my understanding, stack limits are properties of an execution, not of a (module) instance.

**Comment by bddap** [comment]
Looks like someone (@pepyakin according to git blame) had a similar idea when they wrote `common/stack.rs`. `StackWithLimit` is almost the same thing as `BoundedStack`. The main difference is that `BoundedStack` doesn't need its contents to be `Clone` because dummy values aren't used for pre-allocation.

Since we don't need dummy values, `BoundedStack` can contain `FunctionContext` and can be used as a call stack.

I'm going to merge `BoundedStack` into `StackWithLimit` then submit a pr.

**Comment by pepyakin** [comment]
> I've been fiddling with runner.rs and I think it would make most sense to write a stack struct with upper bound checking.

Can you expand a little bit on this? Isn't the current implementation already has upper bounds?

**Comment by bddap** [comment]
Yes, the `ValueStack` struct has upper bounds checking, but the interpreter call stack is currently a `Vec<_>` so it has to be checked manually.

**Comment by pepyakin** [comment]
Ah, I've looked to your implementation and it's looks like the previous implementation of stack with limit, yes : )

The new stack was introduced for optimization in an attempt to remove unnecessary checks that `Vec` does, e.g. to detect the condition for growing. Preallocation up to the specified upper bound allowed us to get rid of that check, AFAIR.

**Comment by pepyakin** [comment]
> When a function calls out to another module, it should provide a new stack with a max size equal to the room left in the current interpreter's stack. 

I'm not sure about that. Why can't it use the same stack? : ) For now it uses the same stack.

> (there's actually a little bug in that logic btw)

Can you tell me more about this one?

**Comment by bddap** [comment]
> I'm not sure about that. Why can't it use the same stack? : ) For now it uses the same stack.

For sandboxing / security. I think the external module shouldn't have access to it's caller stacks. That said, if the external module is validated it could be ok to use the same stack.

> Can you tell me more about this one?

Sure, [line 288](https://github.com/paritytech/wasmi/blob/7b4c648acbd5d2e09a5640139c778b6efdbf95a6/src/runner.rs#L288) checks whether adding two more items to the stack is allowed. If the `nested_func` is a `Internal`, all is well, two items are pushed. If `nested_func` is a `Host` only one item is pushed.

**Comment by bddap** [comment]
> The new stack was introduced for optimization in an attempt to remove unnecessary checks that Vec does, e.g. to detect the condition for growing. Preallocation up to the specified upper bound allowed us to get rid of that check, AFAIR.

I bet the slowness was from needing to constantly re-allocate every time push was called. [Vec::reserve](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.reserve) or [Vec::with_capacity](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.with_capacity) may solve the slowness problem as well.

**Comment by pepyakin** [comment]
> For sandboxing / security. I think the external module shouldn't have access to it's caller stacks. That said, if the external module is validated it could be ok to use the same stack.

Modules are validated at the loading time. In other words, you can't use invalid modules. Besides that, there is no way defined in the spec to operate on stack values that is not produced by the current function (again, given the validness), so I'd say they're already quite isolated.

> Sure, line 288 checks whether adding two more items to the stack is allowed. If the nested_func is a Internal, all is well, two items are pushed. If nested_func is a Host only one item is pushed.

I'm not sure I follow. Why two more items if it says +1? 

> I bet the slowness was from needing to constantly re-allocate every time push was called. Vec::reserve or Vec::with_capacity may solve the slowness problem as well.

I'm not sure that I remember all the details here, but I think we certainly tried to use reserve/with_capacity. But it would be nice I were proven wrong!

**Comment by bddap** [comment]
> Why two more items if it says +1?

Maybe it is only checking for 1. If that's the case, pushing two values is incorrect.

**Comment by barafael** [comment]
Probably related: https://github.com/paritytech/wasmi/issues/259
