### ISSUE TITLE
Question: Why is WasmFuncEntity bound for a instance but HostFuncEntity is not ?

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/wasmi#535]

**Comment by Robbepop** [comment]
The `Store` has ownership of all Wasm related data. The `Instance` has links to the Wasm objects stored in the `Store` that are directly connected to a single Wasm instance. Host functions are simply no Wasm objects since they are originating from the host that drives or uses Wasm.

**Comment by yjhmelody** [comment]
I probably understand it, thank you
