### ISSUE TITLE
I am using resumable functions in smoldot

### ISSUE THREAD

**Issue by tomaka** [paritytech/wasmi#536]
Hi,

The `wasmi` version used in [smoldot](https://github.com/paritytech/smoldot) is terrible outdated.
Unfortunately, I can't update because version 0.14.0 removed "resumable" functions: https://github.com/paritytech/wasmi/blob/master/CHANGELOG.md#removed-1

The way the executor in smoldot works is that we start executing, then as soon as a host function is invoked, the executor interrupts itself and the function that was used to start execution returns. You can then move around the executor and call functions on it while it is in a state where it's waiting for the host function to be resolved. You can then call a function to resume execution, and then when the next host function is invoked, the execution stops again.

I find the pattern used in smoldot significantly better than using callbacks to handle host functions. It provides greater clarity, leads to cleaner code, and avoids tricky issues due to re-entrency.

**Comment by tomaka** [comment]
To be honest I'm a bit shocked that this was simply removed. I've been talking to many people about this better pattern and how "resumable functions" are way superior to what we're doing in Substrate, and I would have expected at least a discussion or a PSA or something, rather than a +124 −13,695 pull request with no description.

**Comment by Robbepop** [comment]
@tomaka Thank you for letting me know about the usage of this feature. Unfortunately it has been removed because nobody ever informed me about use cases. I asked quite a few people but nobody could provide me with a still relevant use case which is why I removed it.
I think it should be possible to add it back to the feature set of the new `wasmi` engine. I left it out mainly because I was not aware of any still relevant use cases and nobody wanted it so far. Also it made some stuff a bit simpler.

What is the priority of upgrading `wasmi` in `smoldot` so that I am aware of how pressing this feature addition is?

**Comment by Robbepop** [comment]
The main complication for the new `wasmi` implementation with respect to resumable functions is that the new `wasmi` implementation reuses the underlying Wasm `Engine` object for calls to Wasm functions whereas the old `wasmi` implementation always spun up an entirely new `Engine`. Obviously spinning up a new `Engine` for every call has severe overhead but also gets rid of lots of other issues when trying to concurrently calling into Wasm.

I will look into how the new `wasmi` implementation can provide a sane API for resumable functions that cannot be easily misused.

**Comment by tomaka** [comment]
Thank you!

> What is the priority of upgrading wasmi in smoldot so that I am aware of how pressing this feature addition is?

I don't need any specific new feature from it, so quite low.
For some reason, dependabot doesn't report new versions of wasmi in the smoldot repository (even though it works for other crates), so I hadn't realized that it was so outdated until this morning.
Looking at the changelog, it seems that there have been many performance improvements, which would obviously be interesting, but that's not a high priority issue.

**Comment by Robbepop** [comment]
> I don't need any specific new feature from it, so quite low.

Okay thanks for letting me know we will still try to get this feature included soon(TM).

> Looking at the changelog, it seems that there have been many performance improvements, which would obviously be interesting, but that's not a high priority issue.

Yeah the whole point of the new `wasmi` implementation was to improve its performance, get rid of deprecated `parity-wasm` and support new Wasm proposals.

**Comment by Robbepop** [comment]
Closing this in favor of https://github.com/paritytech/wasmi/issues/537.
