### ISSUE TITLE
The `Store` is not `Send` nor `Sync`.

### ISSUE THREAD

**Issue by Berrysoft** [paritytech/wasmi#565]
`wasmi` is a great drop-in replacement for `wasmtime` in most cases. However, the type `Store` is not `Send` nor `Sync`, which is the biggest difference. `Store` is used everywhere, and in my use case, `Send` and `Sync` are needed. Although I can `unsafe impl` myself, it would be better to look into the code and find out why they are not implemented.

**Comment by Robbepop** [comment]
Thank you for pointing that out! Since we try to mirror the Wasmtime API as good as we can we want our Store to be Send and Sync. We should look into how we can do that most efficiently.

**Comment by Robbepop** [comment]
May I ask what you are using wasmi for? :)

**Comment by Berrysoft** [comment]
I'm not currently using wasmi (mainly because of the WASI things). However I'd like to try it, because it is an intepreter instead of JIT, which means it could support more platforms.

I'm using WASM for a plugin system in a framework. There are some async and multithreading affairs. It would be good if wasmi supports multithreading by making the types Send and Sync.

**Comment by Robbepop** [comment]
I just created a PR that makes `Store` `Send` and `Sync` and also adds a test that asserts that `Store` remains `Send` and `Sync` in the future. :)
