### ISSUE TITLE
Support `Func::new` style for host function like Wasmtime

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/wasmi#575]
See 
- https://docs.rs/wasmtime/latest/wasmtime/struct.Linker.html#method.func_new
- https://github.com/paritytech/substrate/blob/8016da9ddf1c10a5a74cc5a273905cfeb60ed82c/client/executor/wasmtime/src/imports.rs#L69-L68
In some use cases(including substrate executor), we should allow some host functions are missing or loading lazy.
So we maybe do not care about the signature of host function when allow function missing.
If the host function are hard to be enumerated, it would be impossible to do such things.
`func_new` style api will make user easy to support the above feature.

**Comment by Robbepop** [comment]
Can you elaborate why this API is important? We were just able to port the `contracts-pallet` from legacy `wasmi` to this new `wasmi` API without problems at all.
Best would be a code example that would benefit greatly from having this API in `wasmi`.

**Comment by yjhmelody** [comment]
Not easy to elaborate it. But I'm talking about `sc-executor` part, pallet-contract have no demand to `allow missing host functions`.

**Comment by Robbepop** [comment]
I can see that this API makes this use case a bit simpler but it is not an enabler since it can be worked around, therefore the priority of this issue is low to me.

**Comment by Robbepop** [comment]
I will close this issue now until we are ready to extend our small `wasmi` API. Then we can reopen this again.
