### ISSUE TITLE
`Func::wrap` should support trapped host function

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/wasmi#577]
The host function now could not return a `wasmi_core::Trap`. But wasmtime support it.

**Comment by Robbepop** [comment]
As always please provide a proper description of the requested feature (I cannot understand at all what you want to have), a motivation and rational for it and ideally some example usage and maybe open questions you have.

**Comment by Robbepop** [comment]
Closed because of missing information as stated in https://github.com/paritytech/wasmi/issues/577#issuecomment-1327192946.
