### ISSUE TITLE
WIT support

### ISSUE THREAD

**Issue by flavio** [paritytech/wasmi#657]
As part of the [WebAssembly Component Model](https://github.com/WebAssembly/component-model) proposal, the [WIT](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md) format is used to describe the interfaces used by components.

There's a cli tool, [`wit-bindgen`](https://github.com/bytecodealliance/wit-bindgen) that can to scaffold the import/export code of a certain component.

Currently wit-bindgen can generate export and import code for Wasmtime, but it lacks wasmi support.

In case you're interested, I've created a forked version of wit-bindgen that can generate both import and export code for wasmi.
The code currently lives inside of [this repository](https://github.com/flavio/wit-bindgen/tree/wasmi), under the `wasmi` branch.

wit-bindgen is undergoing a lot of changes. I've targeted the `v0.2.0` release, which is the one used by projects like [Spin](https://github.com/fermyon/spin) and [SpiderLightning](https://github.com/deislabs/spiderlightning).

I will not push the code upstream yet, because of all these undergoing changes (see [this comment](https://github.com/bytecodealliance/wit-bindgen/issues/306#issuecomment-1335854999)).

I'm opening this issue in case other wasmi users could benefit from using this code.

If you want to see the code in action, you can take a look at [this](https://github.com/flavio/hermit-wasm) codebase.

**Comment by flavio** [comment]
I totally understand. The component model is moving damn fast, I expect I'll have to rewrite quite a lot of all the code from my fork.

However, there's just one minor thing that could be done inside of `wasmi`. It would be great to have the equivalent of wasmtime's [`Linker::define`](https://docs.rs/wasmtime/5.0.0/wasmtime/struct.Linker.html#method.define). This is not required (I managed to deal with its lack), but it would make the ergonomics better.

I started to implement it, but then I stopped because 1) I was running out of time for my hackathon 2) I would have broken `wasmi`API.

If you are fine to have this API I would be glad to finish my PR.

**Comment by Robbepop** [comment]
> However, there's just one minor thing that could be done inside of `wasmi`. It would be great to have the equivalent of wasmtime's [`Linker::define`](https://docs.rs/wasmtime/5.0.0/wasmtime/struct.Linker.html#method.define). This is not required (I managed to deal with its lack), but it would make the ergonomics better.
> 
> I started to implement it, but then I stopped because 1) I was running out of time for my hackathon 2) I would have broken `wasmi`API.
> 
> If you are fine to have this API I would be glad to finish my PR.

I am a bit confused about this since the [`Linker::define`](https://docs.rs/wasmi/0.25.0/wasmi/struct.Linker.html#method.define) API exists in `wasmi` already.

**Comment by flavio** [comment]
Sorry, that's entirely my fault... I meant [`Linker::func_wrap`](https://docs.rs/wasmtime/5.0.0/wasmtime/struct.Linker.html#method.func_wrap)

**Comment by Robbepop** [comment]
> If you are fine to have this API I would be glad to finish my PR.

It just occured to me that I have never really answered your question. I was just thinking about this `Linker` API and how we could implement it in `wasmi` when I saw that you apparently seem to have already implemented the whole thing. I could do it, too but I happily accept contributions.

**Comment by flavio** [comment]
On Fri I'll take a look at the code I started writing and I'll let you know. I would like to contribute to the project if time permits :)

**Comment by Robbepop** [comment]
@flavio Could you please move this issue to a discussion item? I think a discussion about `wit-bindgen` support for `wasmi` makes more sense than a technical issue. :)

**Comment by flavio** [comment]
Done, I've created this discussion: https://github.com/paritytech/wasmi/discussions/703

**Comment by Robbepop** [comment]
@flavio Thank you!
