### ISSUE TITLE
Implement Wasmtime's `Func::new` constructor for dynamic function arguments and results

### ISSUE THREAD

**Issue by tomaka** [paritytech/wasmi#658]
Context is me trying to update to a recent version of wasmi in smoldot.

In smoldot, I don't know at compile-time what the types of the functions imported by a wasm module are.
In other words, in smoldot, I don't actually inject strongly-typed functions into a `Linker` or similar. Instead, every host function has the same implementation that manually checks whether the number and the type of the parameters provided by the user corresponds to the function being called.

I don't think it is possible to do that with a recent version of wasmi.
Let me know if I'm wrong, but in order to create a `Func` I need to provide a closure whose parameters and return type match the parameters and return type of the Wasm function. Because I don't know these parameters/return type at compilation time, this isn't possible for me.

**Comment by tomaka** [comment]
One way to circumvent the issue is to have in the source code one closure for each possible combination of parameter and return type, and then have a huge `match` block that picks the correct one at runtime.
This would however be very hacky.

**Comment by Robbepop** [comment]
I guess [this constructor](https://docs.rs/wasmtime/5.0.0/wasmtime/struct.Func.html#method.new) from the Wasmtime API would suffice your needs.
If so this should be fairly straight forward to implement.

**Comment by tomaka** [comment]
> I guess [this constructor](https://docs.rs/wasmtime/5.0.0/wasmtime/struct.Func.html#method.new) from the Wasmtime API would suffice your needs.

Yes :+1:
