### ISSUE TITLE
`wasmi_cli`: Add way to pass/forward WASI arguments

### ISSUE THREAD

**Issue by yamt** [paritytech/wasmi#661]
i tried to run ffmpeg binary from https://github.com/SebastiaanYN/FFmpeg-WASI

```
+ wasmi_cli --dir .video -- .ffmpeg/ffmpeg.wasm -loglevel error -i .video/video-1080p-60fps-2s.mp4 -ss 1 -vframes 1 .video/out.gUIKY3/out-%03d.png
executing File(".ffmpeg/ffmpeg.wasm")::_start() ...
Error: invalid amount of arguments given to function fn _start(). expected 0 but received 9
```

looking at the help text and the code, i couldn't find a way to pass wasi cli arguments.

here is a full script i was using if it matters: https://github.com/yamt/toywasm/blob/5b7f8a870a2b8a7600330f0421b14bf01e2249d8/benchmark/ffmpeg.sh#L48-L54

**Comment by Robbepop** [comment]
Thank you for the bug report. Unfortunately we have not thought about this while adding WASI support to `wasmi_cli`. I consider this to be a bug and we should fix it. What is the command you'd use on the Wasmtime CLI app to invoke `ffmpeg` with those external arguments? (Asking because we basically want to mirror the Wasmtime CLI API as good as we can to keep things simple.)

**Comment by yamt** [comment]
> Thank you for the bug report. Unfortunately we have not thought about this while adding WASI support to `wasmi_cli`. I consider this to be a bug and we should fix it. What is the command you'd use on the Wasmtime CLI app to invoke `ffmpeg` with those external arguments? (Asking because we basically want to mirror the Wasmtime CLI API as good as we can to keep things simple.)

the cli argumens in https://github.com/paritytech/wasmi/issues/661#issue-1578916053 is what works for wasmtime.

my script has the line for wasmtime as well.
https://github.com/yamt/toywasm/blob/5b7f8a870a2b8a7600330f0421b14bf01e2249d8/benchmark/ffmpeg.sh#L68

**Comment by Robbepop** [comment]
Could you please share the exact `.wasm` blob you used for the `ffmpeg`? (Cannot recreate your commands on the repo on my machine atm.) Would appreciate if you could drop it here if possible.

**Comment by yamt** [comment]
> Could you please share the WASI targeting `ffmpeg.wasm` Wasm blob you used? (Cannot recreate your commands on the repo on my machine atm.) Would appreciate if you could drop it here if possible.

download https://assets.runno.dev/ffmpeg/ffmpeg.wasm
place it in .ffmpeg/ dir

download https://github.com/SebastiaanYN/FFmpeg-WASI/raw/4218a47f117df5f900bb2b9bda4f100aa98d1bd7/videos/video-1080p-60fps-2s.mp4
place it in .video/ dir.

```
OUTDIR=$(mktemp -d .video/out.XXXXXX)
```

```
wasmi_cli --dir .video -- \
.ffmpeg/ffmpeg.wasm \
-loglevel error \
-i .video/video-1080p-60fps-2s.mp4 \
-ss 1 -vframes 1 \
${OUTDIR}/out-%03d.png
```

check the output file: ${OUTDIR}/out-001.png

**Comment by yamt** [comment]
btw, if you want to mirror wasmtime cli, why don't you accept `run` subcommand?
eg `wasmtime run ...`
i guess it's their canonical form.

**Comment by Robbepop** [comment]
Their other commands such as `compile` do not make sense for `wasmi` therefore we only use their `run` command which is the default anyways.
