### ISSUE TITLE
Add `wasmi::Linker::func_wrap` method

### ISSUE THREAD

**Issue by Robbepop** [paritytech/wasmi#663]
This allows to define host functions for a `Linker` without the need to associate them to a `Store` and enable cross-store sharing of those host functions.

This feature request came up first in https://github.com/paritytech/wasmi/issues/657#issuecomment-1424006617. Note the explanation of `Linker::define` confusion: https://github.com/paritytech/wasmi/issues/657#issuecomment-1424209114

cc @flavio

**Comment by flavio** [comment]
I looked into the WIP code I had, there's still a lot to be done and I doubt I would be able to get this done quickly. Hence, you can work on this issue @Robbepop.

Once this API is released I'll update my `wit-bindgen` fork to make use of it.

Thanks!

**Comment by Robbepop** [comment]
Okay, will work on it soon(TM).

Looking forward to the `wit-bindgen` update! :)
Any chance your work on `wit-bindgen` might be merged into mainline?

**Comment by flavio** [comment]
> Okay, will work on it soon(TM).

Thanks, no hurries!

> Any chance your work on wit-bindgen might be merged into mainline?

I doubt, from my understanding they want to split the current implementation into modular blocks that would allow everybody to write their own `wit-bindgent`. I think the end goal could be to have my code into a dedicated repository, which would no longer be a fork.

However, thinks are moving really fast and everything keeps breaking in between each iteration.
