### ISSUE TITLE
`wasmi_cli` doesn't preserve WASI exit status

### ISSUE THREAD

**Issue by yamt** [paritytech/wasmi#675]
when a wasi module calls `proc_exit(0)`, wasmi_cli says `Error: failed during execution of _start: Exited with i32 exit status 0` and exit with 1.
it's common for this kind of cli wasm runner programs to relay wasi exit code to host exit(). i guess wasmi_cli should follow the convention.

**Comment by Robbepop** [comment]
Thanks for reporting this `wasmi_cli` bug!

**Comment by yamt** [comment]
> @yamt Thanks a lot for reporting this `wasmi_cli` bug!
> 
> So this means that if a WASI program terminates with `proc_exit(0)` then it returns an error with exit code 0 that is acutally not an error and therefore `wasmi_cli` should not treat it as such?

yes.
the common convention is if a wasi command calls `proc_exit(N)`, the runner program (in this case wasmi_cli) itself exits with exit code `N`.
