### ISSUE TITLE
Update link in repository description

### ISSUE THREAD

**Issue by skammer** [paritytech/wasmi#69]
Right now it points to https://pepyakin.github.io/wasmi/ but should be https://paritytech.github.io/wasmi/

<img width="584" alt="screen shot 2018-02-28 at 20 45 48" src="https://user-images.githubusercontent.com/17655/36803387-73b2296e-1cc8-11e8-8bc9-b1f9375c1412.png">

**Comment by pepyakin** [comment]
Yeah, we definitely should change that! Thanks for the report!

**Comment by pepyakin** [comment]
Updated!
