### ISSUE TITLE
Adjust fuel costs of most instruction to 1 fuel

### ISSUE THREAD

**Issue by Robbepop** [paritytech/wasmi#701]
Currently `wasmi` tries to do a somewhat O.K. job at assigning fuel costs to instructions based on some level of complexity. This includes a base costs for simple instructions such as `i32.add`, a more expensive cost for instructions interacting with Wasm objects such as `global.get` or `table.set`, different costs for function calls and memory loads and stores as well as costs per byte or element for bulk memory and table instructions.

All of this seems to be quite complicated. The gain is that we kind of mirror a rough estimate of how those instructions perform on our native benchmarks.

In contrast Wasmtime simply states that roughly every executed instruction costs 1 fuel. This is super simple and probably is precise enough for most if not all jobs that depend on fuel metering. Obviously it is less precise than what `wasmi` is doing at the moment, but it is to be questioned if that level of precision is actually necessary.

@athei , who is the author of the `contracts-pallet` stated that the Wasmtime approach is likely precise enough for its needs. Therefore we should adjust `wasmi` fuel costs to more closely mirror the fuel costs of Wasmtime's approach.

**Comment by yjhmelody** [comment]
I have done a `step_call` in my fork. No extra instruction, just to count the steps.

**Comment by Robbepop** [comment]
@yjhmelody Could you please elaborate what `step_call` does. I have no idea what you are talking about unfortunately.
