### ISSUE TITLE
Add fuel consumption mode

### ISSUE THREAD

**Issue by Robbepop** [paritytech/wasmi#702]
In the `contracts-pallet` the `wasmi` fuel metering feature is used to "solve" the halting problem for Wasm smart contracts.
For this a UI usually displays the expected costs of a Wasm execution. This is done by dry-running the same Wasm smart contract and displaying the consumed fuel afterwards.
For some of the bulk instructions that `wasmi` supports this fuel consumption is lazy. This means that fuel is only consumed upon a successful execution. For example `memory.grow 1` will only consume fuel if the memory can actually be grown to begin with.

However, it is still checked beforehand if enough fuel for a successful operation is available.
Combined with the dry-running of the Wasm smart contract this means that the estimated amount of fuel required to perform a Wasm smart contract execution can be much lower than what is actually needed if such a bulk operation fails and thus consumes a lot less fuel than needed for successful execution.

A solution to this problem could be to introduce different fuel consumption modes where `Lazy` is the current behavior and `Eager` is a new behavior that simply always consumes the amount of fuel that was consumed if the operation was successful. This way the `contracts-pallet` could perform the dry-run using the `Eager` mode and the actual run using the `Lazy` mode.

A problem with this approach is that `Engine` configurations cannot be changed after the instantiation of an `Engine` and therefore this approach requires to setup two different `wasmi` engines. Would that be a show stopper for you @athei ?

**Comment by athei** [comment]
This will work for me. Thanks.
