### ISSUE TITLE
wasmi-wasi no_std support

### ISSUE THREAD

**Issue by Lucky4Luuk** [paritytech/wasmi#704]
Would it be possible for wasmi-wasi to receive no_std support? It'd be great for implementing wasi, where we define our own implementation of WasiCtx. With wasmi being (one of) the only viable option for running wasm in a no_std environment, this could be a nice addition to the wasmi ecosystem.

**Comment by Robbepop** [comment]
Hi @Lucky4Luuk , I am not sure how this should work since WASI by definition is more or less an POSIX interface that usually requires some kind of OS in the background.
Can you elaborate please?

**Comment by Lucky4Luuk** [comment]
Never mind, I misunderstood how wasmi-wasi worked and was under the impression it was portable to no_std fairly easily. Sorry, closing the issue now.

**Comment by jakehemmerle** [comment]
I believe WASI works in the browser via polyfill or a shim, which could be possibility here

**Comment by Robbepop** [comment]
For our WASI implementation we depend on Wasmtime's `wiggle`, `wasi-cap-std-sync` and `wasi-common` crates. Only if all those crates supported `no_std` we could if we do not want to rewrite all of those crate extensively (which we don't 😅). So as long as those crates do not support `no_std` our WASI implementation does not support it either. Furthermore I still don't know how something like networking or file system access should work with `no_std` in Rust in the first place.
