### ISSUE TITLE
Are async calls from within Wasm code supported?

### ISSUE THREAD

**Issue by huntc** [paritytech/wasmi#715]
Is it possible to support async calls from within wasm code, or is it planned? I suspect not, but ask as wasmtime appears to have support. Thanks.

**Comment by Robbepop** [comment]
For the future: For questions such as these we actually have our discussion forum for `wasmi` in place: https://github.com/paritytech/wasmi/discussions

**Comment by huntc** [comment]
Thanks for the info. 

I did try searching for the place to chat and ending up on Matrix. Looks as though that’s no longer used then. 

Meanwhile, I’ll close this.
