### ISSUE TITLE
Add lazy Wasm compilation

### ISSUE THREAD

**Issue by Robbepop** [paritytech/wasmi#732]
Follow-up from https://github.com/paritytech/wasmi/pull/729.

~~Blocked by: https://github.com/paritytech/wasmi/pull/729~~

Currently `wasmi` always validates and translates Wasm to `wasmi` bytecode for all functions in a Wasm module eagerly.
The advantage of this approach is a simpler architecture, slightly less overhead for direct function calls and better performance in case most or all functions are used upon execution.

[Benchmarks conducted in the `toywasm`](https://github.com/yamt/toywasm/blob/master/benchmark/startup.md) repository showed that Wasm runtimes that employ lazy compilation (and validation) have significantly better startup times which [not significantly reduce their execution performance](https://github.com/yamt/toywasm/blob/master/benchmark/ffmpeg.md#result). Also their memory consumption is not inflated either.

Despite the performance improvements as indicated by the above benchmarks `wasmi` does not employ lazy compilation. One reason is that `wasmi` bytecode and its translation is fairly simple. With the future shift towards [register-machine `wasmi` bytecode](https://github.com/paritytech/wasmi/pull/729) the compilation overhead is going to be significantly higher compared to the current stack-machine based `wasmi` bytecode architecture and it would make lazy compilation likely very advantageous.

This issue tracks progress of lazy compilation.

**Comment by tomaka** [comment]
I just wanted to mention that the smoldot light client would hugely benefit from this feature.

At initialization, smoldot downloads and compiles the runtime of a chain. The runtime is typically around 1.0 to 1.5 MiB, and this takes around 300ms-400ms on my machine.

After initialization, smoldot only executes very small functions from this runtime (typically small getters).

In the case of smoldot, the initialization is what matters the most. 300ms-400ms isn't that much, but smoldot wants to support connecting to dozens of chains at the same time (so dozens of runtimes), and this compilation time quickly adds up.

**Comment by Robbepop** [comment]
@tomaka Thanks a lot for letting me know about your use case.

The [register machine `wasmi`](https://github.com/paritytech/wasmi/pull/729) is certainly going to add some compilation time overhead, therefore the lazy compilation strategy is needed in order to balance out the incoming regressions.

Note that Wasm validation will still be eager and thus there 300-400ms will not evaporate entirely. :D

**Comment by tomaka** [comment]
> Note that Wasm validation will still be eager and thus the 300-400ms smoldot runtime startup time will probably not evaporate entirely.

Is it not possible to disable the validation as well?

> One drawback with lazy Wasm compilation is that the translation process might fail, for example due to overflowing wasmi limits and if the compilation is interleaved with execution, then execution might fail.

It is already not possible for smoldot (or Substrate for that regard) to guarantee ahead of time that execution will succeed.
If the runtime has a bug, execution can fail for example because it panics or because it calls an imported function with invalid parameters or because it reads memory out of bounds.

The fact that the Wasm compilation might fail at execution time is just an extra possible reason why execution can fail. Given that there are already reasons why execution might fail, it really doesn't change much. It's all under the same "the runtime has a bug" umbrella of reasons.

Similarly, it would also be ok (for smoldot) if a bad Wasm bytecode (for example an invalid opcode) fails at execution time as well.

**Comment by Robbepop** [comment]
> Is it not possible to disable the validation as well?

No. While partial Wasm validation is part of the Wasm spec it is also highly controversial and leaders in the Wasm ecosystem say that it was allowed to satisfy some authors of a runtime back in the days and that runtime doesn't even exist anymore today. The only runtime I know of that has partial Wasm validation is Wasm3.

**Comment by tomaka** [comment]
I can imagine that there could be risks in executing a single function of Wasm blob that hasn't been fully validated.

However here the Wasm blob *has* been fully validated. Just not by the local machine.

Furthermore, since wasmi is an interpreter, I don't really see what the "risk" could be except for the fact that execution could succeed when it normally shouldn't.

**Comment by Robbepop** [comment]
> Furthermore, since wasmi is an interpreter, I don't really see what the "risk" could be except for the fact that execution could succeed when it normally shouldn't.

The `wasmi` bytecode executor has some `unsafe` parts that rely on Wasm validation to be correct. If you view `wasmi` in isolation it is simply not a good idea to take off this mandatory safety belt. There is a reason why no major Wasm runtime implements partial Wasm validation.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/smoldot-updates-threads/4471/12

**Comment by Robbepop** [comment]
All blockers have been resolved and it is now time to (finally) work on this issue.

**Comment by Robbepop** [comment]
I was able to conduct initial benchmarks in https://github.com/paritytech/wasmi/pull/844.

**Comment by Robbepop** [comment]
@tomaka I am mostly done implementing #844.

Benchmark results on our CI machines indicate far better speed-ups than on my local machine:

- `Spidermonkey.wasm` timings:

    - `checked` + `eager` + `fueled`: 82.22ms
    - `checked` + `lazy`: 32.64ms (2.5x)
    - `unchecked` + `lazy`: 3.05ms (27x)

- ERC-20 timings:

    - `checked` + `eager` + `fueled`: 142.15µs
    - `checked` + `lazy`: 65.85µs (2.15x)
    - `unchecked` + `lazy`: 19.09µs (7.4x)

**Comment by tomaka** [comment]
Ah great!

If I use `unchecked` but that in reality it turns out that the Wasm is invalid, what can happen?

**Comment by Robbepop** [comment]
> Ah great!
> 
> If I use `unchecked` but that in reality it turns out that the Wasm is invalid, what can happen?

There be dragons. Undefined behavior at its finest.

**Comment by tomaka** [comment]
I see, so this doesn't fit smoldot, but I can use `lazy`.

**Comment by Robbepop** [comment]
Are you able to use multiple threads? In this case I could implement parallel Wasm validation since that would greatly help.

**Comment by tomaka** [comment]
No

**Comment by Robbepop** [comment]
Due to https://github.com/WebAssembly/design/issues/1464 I did not implement partial Wasm validation for `Module::new`, however, technically we could implement it in Wasmi without much implementation burden from what I would say.

However, the reasons against partial Wasm validation are ... valid ... in my opinion and I think it can be dangerous to go there.
I just released Wasmi `v0.32.0-beta.0` to crates.io. In case you test it out I would love feedback on the improved startup times. Also I'd like to know if you want me to implement partial Wasm validation support in Wasmi even though it is a controversial topic.

**Comment by tomaka** [comment]
I don't really understand why you're okay with implementing `unchecked` but you're not okay with partial validation. To me, `unchecked` is in every way "worse" (according to the arguments in the issue you've linked) than partial validation.

---

I also don't really understand the argument against partial validation.

As a counter-argument: the runtime Wasm has some imported functions at its disposal, and the parameters that the runtime passes when it calls an imported function must obey certain rules (depending on which function is called). For example, some parameters have to be a valid pointer, or be within a certain range. Failing to do so leads to a trap. It's obvious that it's not possible to determine ahead of time whether these parameters are valid, it's only ever evaluated lazily.
Given that the parameters are evaluated lazily, there might be code in the runtime that is completely invalid and left undetected.
Why would it be important to be sure that the Wasm bytecode is valid everywhere, while at the same time we're not sure that the logic expressed by this bytecode isn't valid?

**Comment by tomaka** [comment]
As far as I understand, the main argument against partial validation is:

> A concrete issue would be if a widely used module has a function with a validation error in it, but the function is never called in practice. On an engine with lazy validation, the module would run fine. On an engine with eager validation, the module would fail to compile and the web page would be broken. In order to resolve this, the second engine would need to implement lazy validation even if it doesn't make sense in their compilation model.

Indeed, when a runtime upgrade happens, the new runtime would have to be compiled with eager validation.

In the case of the smoldot light client, though, the situation is that at least 2/3rds of the validators of the network have declared "this wasm is valid". And the smoldot light client is based upon the assumption that at least 2/3rds of the validators are honest, otherwise everything is lost. It seems to 100% fit within the partial validation situation.

I'm not ok with "unchecked" validation, because 1) we want to gracefully inform the user if a chain turns out to be broken rather than go into undefined behavior 2) the same instance of smoldot can be used to connect to multiple chains, and if one chain is broken we don't want the other chain connections to be affected.

**Comment by Robbepop** [comment]
> I don't really understand why you're okay with implementing `unchecked` but you're not okay with partial validation. To me, `unchecked` is in every way "worse" (according to the arguments in the issue you've linked) than partial validation.

Okay let me elaborate on my design thoughts.

The goal is to avoid partial Wasm validation while allowing for the fastest possible compilation performance when possible.
So we provide two mechanisms:

1) lazy compilation with eager Wasm validation which is faster than eager compilation and safe.
2) lazy compilation without Wasm validation for when users can safely assume their Wasm inputs to be valid Wasm.

In case of the `pallet_contracts` 2) is applicable because it has full control over its input Wasm blobs.
In smoldot I agree that you shouldn't use unchecked Wasm validation since it seems that you do not have this "full control" over the input Wasm blobs.

Therefore the middleground solution with lazy compilation & validation would probably make sense for you.
