### ISSUE TITLE
What is the reason for the outdated WASI runtime dependencies of `wasmi`?

### ISSUE THREAD

**Issue by ShaleXIONG** [paritytech/wasmi#736]
Hi, 
is there any plan to update the wasi-related dependencies to a later version, for example, ^9?

**Comment by Robbepop** [comment]
I have not looked into this for a long while but my last understanding of the situation was that the WASI libraries that we use in `wasmi` for the WASI runtime started to introduce a hard-dependency on Wasmtime which disallowed us to further update then unless we want to maintain our own fork of them. But that's nothing I am looking forward to so we are just stuck to those versions for now until the hard-dependency on Wasmtime is resolved.

**Comment by Robbepop** [comment]
@ShaleXIONG Can this issue be closed?
