### ISSUE TITLE
Does `wasmi` support the Wasm `multi-value` proposal?

### ISSUE THREAD

**Issue by deadblackclover** [paritytech/wasmi#739]
Is there Multi-value support in `wasmi`? If not, is it planned to implement it?

[The multi-value proposal](https://github.com/WebAssembly/spec/pull/1145) in WebAssembly

**Comment by Robbepop** [comment]
Yes, `wasmi` supports the Wasm `multi-value` proposal and it is even enabled by default. The README displays information about all the supported Wasm proposals: https://github.com/paritytech/wasmi#webassembly-proposals
