### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by tailhook** [paritytech/wasmi#74]
Is there anything that blocks a new release now?

In particular I'm interested in https://github.com/paritytech/wasmi/issues/41

**Comment by pepyakin** [comment]
Hey! Before the release, we wanted to fix `parity-wasm` (see https://github.com/paritytech/wasmi/issues/37).

However, since the fix for parity-wasm most likely will be a patch release I guess we can publish wasmi before that...

**Comment by tailhook** [comment]
Well, I realized my project isn't on crates.io. So I can stick with git version for now. No hurry.

**Comment by pepyakin** [comment]
btw, 0.1.0 has been released.
