### ISSUE TITLE
Hangs out while executing the given testcase

### ISSUE THREAD

**Issue by luxinyi0105** [paritytech/wasmi#750]
### Describe the bug
While executing the [given wasm file](https://github.com/luxinyi0105/wasm_runtime_test/raw/main/08-01.zip), wasmi hangs out and does not end. 

### Versions and Environment
Tools version: wasmi_cli 0.30.0
Operating system: Ubuntu 22.04.1
Architecture: x86_64

### Current behavior
```sh
$ wasmi_cli mutated.wasm
executing File("mutated.wasm")::_start() ...
```
It will hang out and does not end.

### Expected
I used some other WebAssembly Runtimes, e.g. wasmer and wasmtime, to execute the same testcase. They will terminate the execution of the wasm file in approximately 8-10 seconds, and do not output anything. I am not sure if their behaviour is correct, but it seems that "hang out" is not a good choice. So, in this sense, maybe their behaviour is expected. 

### Additional context
Actually, the given testcase was simply mutated a wasm file, which was obtained by compiling the C program generated with Csmith using the Emscripten compiler(Emcc). You can convert wasm file to wat format with wabt and find the mutation operation in line 2326(replace i32.sub with i32.div_s). Releated files are in the zip file.

**Comment by luxinyi0105** [comment]
> Thanks for the testcase! Indeed sounds weird if both Wasmtime and Wasmer hold after roughly 10 seconds and `wasmi` seemingly runs forever. How long have you tried running the `wasmi` process before declaring that it won't stop? Generally `wasmi` being an interpreted runtime is orders of magnitude (usually between x20-x30) times slower than JIT based Wasm runtimes such as Wasmtime or Wasmer.
> 
> Also does this problem persist with the newest `wasmi` version `v0.31.0`, too? How did you install `wasmi`? I ask because if `wasmi` was installed incorrectly some optimizations may be missing which are greatly needed for performance of `wasmi`.

Based on the phenomenon in #751, the problem has been resolved. 

It will take about 2 m 48 s to execute the given wasm file and then terminate the execution process without output anything. Thanks a lot!

**Comment by Robbepop** [comment]
> It will take about 2 m 48 s to execute the given wasm file and then terminate the execution process without output anything. Thanks a lot!

Glad to hear!

Timing are also within the expected slowdown of x20-30 compared to JIT based runtimes. :)
