### ISSUE TITLE
Different result from other wasm runtimes while executing the given wasm file

### ISSUE THREAD

**Issue by luxinyi0105** [paritytech/wasmi#752]
### Describe the bug

While executing the given testcase with wasmi and some other runtime tools, the results are different. 

### Test Case

The given [testcase](https://github.com/luxinyi0105/wasm_runtime_test/raw/main/08-27.zip) was simply mutated a wasm file, which was obtained by compiling C program generated with `Csmith` using `Emscripten Compiler`(Emcc). 

The original C program is `c_file.c`, the compilation results with Emscripten is `wasm_file.wasm`, and its wat format is `wat_file.wat`. 

We mutated the wat file to change its `global.set 0` in line 7627 with `local.set 0`. The result after mutation is `mutated_file.wat`, and its wasm format is `mutated_file.wasm`.

### Versions and Environment

Tools version: wasmi_cli 0.31.0
Operating system: Ubuntu 22.04.1
Architecture: x86_64

### Expected behavior

```sh
$ wasmi_cli mutated_file.wasm
executing File("mutated_file.wasm")::_start() ...
checksum = 61D81D2D
```

### Actual behavior

```sh
$ wasmi_cli mutated_file.wasm
executing File("mutated_file.wasm")::_start() ...
checksum = 61D81D2D
Error: failed during execution of _start: exit with invalid exit status outside of [0..126)
```

### Additional context

I tried to use some other wasm runtimes, such as wasmer, wasmedge and wasm-micro-runtime(WAMR) to execute the same testcase, they just output the checksum result and do not trigger errors. 

It seems that there is something wrong with the “exception handling module”, but I am not sure if the problem lies in wasmtime or other runtime tools due to a lack of understanding of WebAssembly. So the details still need you to confirm. Thanks a lot!

**Comment by Robbepop** [comment]
I found this similar issue by you for Wasmtime: https://github.com/bytecodealliance/wasmtime/issues/6919
And I think the same reasoning that [@alexcrichton provides in his statement](https://github.com/bytecodealliance/wasmtime/issues/6919#issuecomment-1695816895) applies equally to `wasmi` which makes sense given that `wasmi` simply uses the WASI implementation that is also used by Wasmtime thus checking the status exit code and thus doing apparently the right thing here.

**Comment by Robbepop** [comment]
Closed due to previous comment.
