### ISSUE TITLE
Any plan that try to support simd?

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/wasmi#762]
I think the feture is good to improve performance. It just like composing multi instrutions into a big one. It could also improve speed, even just a direct normal implamentation in `no_std` IMO.

**Comment by Robbepop** [comment]
I am personally not convinced of 128-bit SIMD to be a future proof Wasm proposal. Furthermore its ratio between additional complexity and gained performance is also very low in my honest opinion. So maybe we add it but it is very low on our priority list.

**Comment by yjhmelody** [comment]
Nice! First time see this proposal.

**Comment by Robbepop** [comment]
> Nice! First time to see this `flexible-vectors` proposal. Will it be a standard soon?
> 
> I agree with you.

It won't be in the standard soon enough since it is still phase 1.
