### ISSUE TITLE
Why need  MemoryInstance::copy and MemoryInstance::copy_nonoverlapping

### ISSUE THREAD

**Issue by dingelish** [paritytech/wasmi#80]
Hi there,

wasmi seems pretty much interesting. I'm looking into it's implementation. I found that `MemoryInstance::copy` and `MemoryInstance::copy_nonoverlapping` are used nowhere and can be removed along with their unit tests. All tests passed. My question is: are they essential in this project? Could I remove them? Thanks!

**Comment by pepyakin** [comment]
Hey!

They might be used by dependent projects, e.g. in [polkadot](https://github.com/paritytech/polkadot/blob/3d4694844f5309b5373ca3c7f2861c9a2f31cce4/substrate/executor/src/wasm_executor.rs#L151).

I'm wondering, why do you need to remove these?
