### ISSUE TITLE
Experiment with partial Wasm validation compilation mode

### ISSUE THREAD

**Issue by Robbepop** [paritytech/wasmi#853]
In discussions in https://github.com/paritytech/wasmi/issues/732 (https://github.com/paritytech/wasmi/issues/732#issuecomment-1859295561) it was found that the current lazy compilation setup with either eager Wasm validation or no validation at all doesn't make sense for some users of Wasmi, e.g. smoldot.

Therefore we want to experiment with partial Wasm compilation & validation modes which are nearly as fast as the unchecked versions but can be applied when it is not safe to assume that Wasm inputs are valid.

Note that partial Wasm validation is a controversial topic:
https://github.com/WebAssembly/design/issues/1464

CC @tomaka

**Comment by tomaka** [comment]
> Note that partial Wasm validation is a controversial topic:
https://github.com/WebAssembly/design/issues/1464

I think the controversy is mostly related to the fact that all browsers must behave the same way when executing a wasm.
In other words, the only thing to be aware of is that lazy validation mode must not be used when the result of Wasm execution must be deterministic amongst multiple implementations.

I don't think there's any problem in adding a mode for people who know what they're doing, and I don't think that it helps to say "this is a controversial option" without an explanation.
