### ISSUE TITLE
Impossible to build an `Error` containing a `Box<dyn HostError>`

### ISSUE THREAD

**Issue by tomaka** [paritytech/wasmi#855]
`wasmi::Func::new` requires passing a closure that returns a `Result<(), Error>`.
Previously, the error type was `Trap`, which is easy to build.

Now that it is `Error`,  it is not possible anymore to build an error containing a `Box<dyn HostError>`.

Basically, `Error::from_kind` or a similar function should be public.

**Comment by Robbepop** [comment]
Thanks for reporting! This indeed was an oversight. Will fix asap.
